pretrain_use: False
num_epochs: 100
num_classes: 3
batch_size: 32
learning_rate: 1e-12
max_distance: 5
action_file_path: /home/user/src/Cognitive-Map/experiment/data
test_action_file_path: /home/user/src/Cognitive-Map/experiment/data/test_dataset
